// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"binancedata/internal/biz"
	"binancedata/internal/conf"
	"binancedata/internal/data"
	"binancedata/internal/server"
	"binancedata/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	client := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db, client)
	if err != nil {
		return nil, nil, err
	}
	binanceDataRepo := data.NewBinanceDataRepo(dataData, logger)
	binanceDataUsecase := biz.NewBinanceDataUsecase(binanceDataRepo, logger)
	binanceDataService := service.NewBinanceDataService(binanceDataUsecase)
	httpServer := server.NewHTTPServer(confServer, binanceDataService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
